### ISSUE TITLE
Videos stays on "Loading..."

### ISSUE THREAD

**Issue by ghost** [sixem/ivfi-node#10]
Honestly, I don't know if this is a bug or is it related to my internet, but videos seems to be loading infinitely after watching one video after reloading the page. Is this a known bug? My nodexer is hosted at [files.drivet.xyz](https://files.drivet.xyz/). I can try giving more details if needed.
![https://cloud.drivet.xyz/waXA3/TelIhEyI64.png](https://cloud.drivet.xyz/waXA3/TelIhEyI64.png/raw)

**Comment by sixem** [comment]
It's a bit late, but this package has been rewritten and updated now. This issue should hopefully no longer be a problem.

I don't expect a reply since this is quite an old issue now and the source code is very different now, so I'll just go ahead and mark this as completed. If this problem still persists for anyone, feel free to open it again.
